version: '3.8'
services:
  etherminer:
    image: etherminer
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    privileged: true
    restart: always
    command: /usr/local/bin/ethminer -U -S $POOL1 -FF $POOL2 -O $ETH_WALLET.$WORKERNAME --cuda -RH -SP 1 --cuda-parallel-hash 4
 
